version: "3.8"

services:
  api:
    image: dogsitter-api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__db: "Host=db.nvfvezcvzsrhconbxcpv.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=oWZz3EcdlD1MmRdF;SSL Mode=Require;Trust Server Certificate=true"
